**Alt arrayde degişiklik yaptıgımızda ana arrayda degişiklik olmamasını için**

In [1]:
import numpy as np

In [3]:
a=np.random.randint(10,size=(3,5))
a

array([[0, 6, 8, 6, 5],
       [1, 0, 9, 9, 6],
       [9, 5, 2, 6, 5]])

In [6]:
alt_array=a[0:2,0:3].copy()

In [7]:
alt_array

array([[0, 6, 8],
       [1, 0, 9]])

In [10]:
alt_array[0,0]=4

In [11]:
alt_array

array([[4, 6, 8],
       [1, 0, 9]])

In [12]:
a

array([[0, 6, 8, 6, 5],
       [1, 0, 9, 9, 6],
       [9, 5, 2, 6, 5]])