**Local Outlier Factor**

Bir noktanın local yoğunluğu bu noktanın komşularıyla karşılaştırılıyor.Eğer bir nokta komşularının yoğunluğundan anlamlı bir şekilde düşük ise bu nokta komşularından daha seyrek bir bölge de bulunuyordur yorumu yapılabiliyor.Dolayısıyla burada bir komşuluk yapısı söz konusu.Bir değerin çevresi yogun degilse demek ki bu değer aykırı değerdir şeklinde değerlendirliyor.

In [5]:
import seaborn as sns
import numpy as np
from sklearn.neighbors import LocalOutlierFactor #kullanarak bir skorlama işlemi gerçekleştireceğiz

In [12]:
veri=sns.load_dataset("diamonds")
veri=veri.select_dtypes(include=["float64","int64"]) #sayısal verilere erişmek için tip seçimi gerçekleşitiriyor
veri=veri.copy()
veri=veri.dropna() #eksik değerleri silmek için
veri.head()

carat  depth  table  price     x     y     z
0   0.23   61.5   55.0    326  3.95  3.98  2.43
1   0.21   59.8   61.0    326  3.89  3.84  2.31
2   0.23   56.9   65.0    327  4.05  4.07  2.31
3   0.29   62.4   58.0    334  4.20  4.23  2.63
4   0.31   63.3   58.0    335  4.34  4.35  2.75

In [13]:
lof=LocalOutlierFactor(n_neighbors=20,contamination=0.1) #n_neighbors komşuluk sayısını belirtiyoruz.contamination yogunlugu ifade eder.

In [14]:
lof.fit_predict(veri) #algoritmayı çalıştırma işlemi

array([-1, -1, -1, ...,  1,  1,  1])

In [15]:
veri_scores=lof.negative_outlier_factor_

In [17]:
veri_scores[1:10]

array([-1.59732899, -1.62278873, -1.33002541, -1.30712521, -1.28408436,
       -1.28428162, -1.26458706, -1.28422952, -1.27351342])

In [18]:
np.sort(veri_scores[1:20])

array([-1.62278873, -1.59732899, -1.33002541, -1.30712521, -1.28428162,
       -1.28422952, -1.28408436, -1.27351342, -1.26458706, -1.23611906,
       -1.21093135, -1.20830179, -1.17637026, -1.14305176, -1.13307628,
       -1.13060731, -1.11364018, -1.08139269, -1.08093519])