In [2]:
import numpy as np

In [3]:
x=np.array([1,2,3,4,5])
y=np.array([6,7,8,9,10])

In [4]:
np.concatenate([x,y])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
z=np.array([11,12,13])

In [7]:
np.concatenate([x,y,z])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

İki Boyutta Birleştirme

In [17]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[10,11,12],[13,14,15],[20,21,25]])

In [18]:
np.concatenate([a,b]) #satur olarak birleştirdi

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [20, 21, 25]])

In [26]:
np.concatenate([a,b],axis=1)

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 20, 21, 25]])