In [1]:
import numpy as np

5*x0 + x1=12

x0 + 3*x1=10

In [9]:
a=np.array([[5,1], [1,3]]) #Katsayıları yazdık
b=np.array([12,10]) #Sonuçları yazdık

In [5]:
a

array([[5, 1],
       [1, 3]])

In [6]:
b

array([12, 10])

In [10]:
cöz=np.linalg.solve(a,b) #linalg.solve çözdü
cöz

array([1.85714286, 2.71428571])