In [1]:
import numpy as np

In [3]:
a=np.random.randint(10,size=12)
a

array([7, 0, 9, 0, 0, 5, 4, 4, 8, 9, 1, 2])

In [4]:
a[2]

9

In [5]:
a[-2]

1

In [6]:
a[0]=25

In [7]:
a

array([25,  0,  9,  0,  0,  5,  4,  4,  8,  9,  1,  2])

**İki Boyutlu**

In [14]:
b=np.random.randint(9,size=(7,3))
b

array([[1, 0, 3],
       [3, 5, 3],
       [1, 3, 0],
       [3, 4, 6],
       [0, 1, 7],
       [3, 2, 2],
       [0, 4, 8]])

In [15]:
b[0,0]

1

In [16]:
b[2,0]

1

In [17]:
b[3,2]

6

In [18]:
b[3,2]=5

In [19]:
b

array([[1, 0, 3],
       [3, 5, 3],
       [1, 3, 0],
       [3, 4, 5],
       [0, 1, 7],
       [3, 2, 2],
       [0, 4, 8]])

In [21]:
b[2,0]=4.5

In [22]:
b

array([[1, 0, 3],
       [3, 5, 3],
       [4, 3, 0],
       [3, 4, 5],
       [0, 1, 7],
       [3, 2, 2],
       [0, 4, 8]])