In [1]:
import numpy as np

In [2]:
a=np.arange(0,30,3)
a

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [4]:
al_getir=[1,2,3]

In [5]:
a[al_getir]

array([3, 6, 9])

In [6]:
a

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

**İki Boyut**

In [9]:
b=np.arange(9).reshape((3,3))
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
satir=np.array([0,1])
sutun=np.array([1,2])

In [13]:
b[satir,sutun]

array([1, 5])