In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

**UFUNC**

In [5]:
np.add(a,1) #TOPLAMA

array([2, 3, 4, 5, 6])

In [7]:
np.subtract(a,1) #ÇIKARMA

array([0, 1, 2, 3, 4])

In [8]:
np.multiply(a,4) #ÇARPMA

array([ 4,  8, 12, 16, 20])

In [9]:
np.divide(a,2)

array([0.5, 1. , 1.5, 2. , 2.5])

In [10]:
np.power(a,3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [11]:
np.mod(a,5)

array([1, 2, 3, 4, 0], dtype=int32)

In [12]:
np.absolute(np.array([-3,-2]))

array([3, 2])

In [13]:
np.sin(360)

0.9589157234143065

In [14]:
np.cos(180)

-0.5984600690578581

In [15]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [16]:
np.log10(a)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ])

In [17]:
?np

Type:        module
String form: <module 'numpy' from 'C:\\Users\\buse\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\buse\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>>

In [18]:
np.mean(a)

3.0