In [2]:
import numpy as np

In [4]:
a=np.array([3,4,3.15,2.11])
a

array([3.  , 4.  , 3.15, 2.11])

In [7]:
b=np.array([2,4,5,7, 1.25 , 2.47],dtype="int")#float değerleri int dönüştürür.float yapmak içinse float32
b

array([2, 4, 5, 7, 1, 2])

**Sıfırdan Array Oluşturma**

In [24]:
np.zeros(10,dtype=int) #Tek boyutlu array(vektör)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
np.ones((3,5),dtype=int) #İki boyutlu array(mantris)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [13]:
np.full((3,5),5,dtype=int)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [16]:
np.arange(0,30,3) #Dogrusal array oluşturma

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [19]:
np.linspace(0,2,10) #İki değer arasında belirli sayıda değer oluşturma

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [27]:
np.random.normal(10,5,(2,3)) #10=ort 5=standart sapma (2,3)=satır sütün

array([[ 6.25135726, 12.43472889, 12.11958026],
       [14.10286418,  6.95981593,  8.45985738]])

In [38]:
np.random.randint(0,10,(3,3)) #int tipinde rastgele array 

array([[1, 6, 1],
       [6, 4, 6],
       [5, 4, 9]])

*************************************************************************************************************

In [47]:
p=np.random.randint(9,size=10)

In [43]:
p.ndim #Tek boyutlu oldugu için 1

1

In [44]:
p.shape

(10,)

In [45]:
p.size #toplam elaman sayısı

10

In [46]:
p.dtype #veri tipini verdi

dtype('int32')

------------------------------------------------------------------

In [49]:
n=np.random.randint(10,size=(10,3))

In [50]:
n

array([[4, 9, 4],
       [6, 4, 6],
       [8, 5, 8],
       [3, 6, 4],
       [7, 7, 4],
       [2, 9, 2],
       [7, 0, 9],
       [2, 6, 6],
       [2, 0, 4],
       [9, 7, 2]])

In [51]:
n.ndim #2 boyutlu 

2

In [52]:
n.shape

(10, 3)

In [53]:
n.size

30

In [54]:
n.dtype

dtype('int32')