**Bazen tek boyuttan çok boyuta bazen çok boyuttan tek boyuta çevirmemiz gerekebiliyor. Bunun için ihtiyaç.**

In [1]:
import numpy as np

In [11]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
a.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
b=np.arange(1,10) #Boyut 2 çıktı.Mantris oldu
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
c=b.reshape((1,9))

In [21]:
c.ndim

2