In [1]:
import numpy as np

In [7]:
a=np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a[1:6]

array([1, 2, 3, 4, 5])

**İki Boyut**

In [9]:
b=np.random.randint(20,size=(5,4))
b

array([[ 1, 18, 17, 19],
       [13,  2, 12, 14],
       [ 0, 11,  8, 14],
       [14, 15,  1,  6],
       [ 0,  5,  1,  0]])

In [10]:
b[:,0] #bütün satırları seç.0. sütün

array([ 1, 13,  0, 14,  0])

In [11]:
b[0,:]

array([ 1, 18, 17, 19])

In [12]:
b[0:2,1:3:]

array([[18, 17],
       [ 2, 12]])