In [1]:
import numpy as np

In [2]:
a=np.array([2,4,7,5,1,0,3,6])

In [3]:
a

array([2, 4, 7, 5, 1, 0, 3, 6])

In [6]:
np.sort(a)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [7]:
a

array([0, 1, 2, 3, 4, 5, 6, 7])

**İki Boyutlu Sıralama**

In [12]:
b=np.random.normal(20,5,(4,4)) #20 ort 5 standart sapma
b

array([[16.84715385, 22.29555248, 15.33206337, 30.47908573],
       [29.32011012, 24.72129715, 14.55264466, 14.61840644],
       [22.47791234, 12.89686044, 16.22562338, 20.12472084],
       [23.42693916, 18.12347303, 26.85578899, 28.14366002]])

In [14]:
np.sort(b,axis=1) #satır satır göre sıralama

array([[15.33206337, 16.84715385, 22.29555248, 30.47908573],
       [14.55264466, 14.61840644, 24.72129715, 29.32011012],
       [12.89686044, 16.22562338, 20.12472084, 22.47791234],
       [18.12347303, 23.42693916, 26.85578899, 28.14366002]])

In [15]:
np.sort(b,axis=0) #sütünlara göre sıralama

array([[16.84715385, 12.89686044, 14.55264466, 14.61840644],
       [22.47791234, 18.12347303, 15.33206337, 20.12472084],
       [23.42693916, 22.29555248, 16.22562338, 28.14366002],
       [29.32011012, 24.72129715, 26.85578899, 30.47908573]])