In [1]:
import numpy as np

In [3]:
x=np.array([1,2,3,4,4,3,2,1])

In [7]:
np.split(x,[2,3,4])

[array([1, 2]), array([3]), array([4]), array([4, 3, 2, 1])]

**Çıktıyı Saklama**

In [9]:
a,b,c,d=np.split(x,[2,3,4])

In [10]:
a

array([1, 2])

In [11]:
b

array([3])

In [12]:
c

array([4])

In [13]:
d

array([4, 3, 2, 1])

**İki Boyutlu Ayırma İşlemi**

In [16]:
y=np.arange(20).reshape(5,4)
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [19]:
np.vsplit(y,[2]) 

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [28]:
ust,alt=np.vsplit(y,[2]) #yandan böldü

In [21]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [22]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [23]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [29]:
np.hsplit(y,[2]) #dik böldü

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19]])]

In [25]:
sag,sol=np.hsplit(y,[2])

In [26]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17]])

In [27]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])